name: 'pull request'

on:
  pull_request

jobs:
  build:
    name: 'push and release'

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
      shell: bash
    - name: build
      run: python3 setup.py build
      shell: bash
    - name: test
      run: |
        pytest
      shell: bash
